from __future__ import annotations


REPORT_TYPES = {"drilling", "completion", "workover"}

REPORT_TYPE_ORDER = ("drilling", "completion", "workover")

COMMON_FIELD_COLUMNS = [
    "record_id",
    "event",
    "reportDate",
    "reportNo",
    "wellbore",
    "rig",
    "primaryReason",
    "afeNumber",
    "refDatum",
    "currentOps",
    "summary24h",
    "forecast24h",
    "otherRemarks",
]

DRILLING_FIELD_COLUMNS = COMMON_FIELD_COLUMNS + [
    "wellboreNo", "dfs", "todayMd", "prevMd", "progress", "rotHrsToday", "avgRopSlide", "avgRopRot",
    "dailyCost", "cumulativeCost", "afeCost", "supervisor1", "supervisor2", "engineer", "pamEngineer",
    "geologist", "totalPersonnel", "lastCasing", "lastCasingSize",
    "lastCasingDepth", "nextCasing", "nextCasingSize", "nextCasingDepth", "formTestType", "formTestEmw",
    "lastBopPressTest", "pumpRate", "pumpPress", "stringWeightUp", "stringWeightDown",
    "stringWeightUpDown", "torqueOffBottom", "torqueOnBottom",
    "mudEngineer", "sampleFrom", "mudType", "mudTime", "mudMd", "mudDensity",
    "mudTemperature", "rheologyTemp", "viscosity", "pv", "yp", "gel10s", "gel10m",
    "gel30m", "apiWl", "oilPercent", "waterPercent", "sand", "ecd", "mudComments",
    "bitNo", "bitSize", "bitManufacturer", "bitSerial", "bitWearIodl", "bitWearBgor", "bhaNo", "bhaMdIn",
    "bhaMdOut", "bhaTotalLength", "safetyIncident", "environmentIncident",
    "daysSinceRi", "daysSinceLta", "incidentComments", "groundElev", "afeMdDays",
]

COMPLETION_FIELD_COLUMNS = COMMON_FIELD_COLUMNS + [
    "completionNo", "wellboreNo", "groundElev", "dol", "dfs", "rigContractName",
    "description", "operationStartDate", "afeCost", "dailyCost", "cumulativeCost",
    "supervisor1", "supervisor2", "engineer", "pamEngineer", "geologist",
    "totalPersonnel", "safetyComments",
]

WORKOVER_FIELD_COLUMNS = COMMON_FIELD_COLUMNS + [
    "workoverNo", "wellboreNo", "groundElev", "dol", "dfs", "rigContractName",
    "description", "operationStartDate", "afeCost", "dailyCost",
    "cumulativeCost", "supervisor1", "supervisor2", "engineer", "pamEngineer",
    "geologist", "totalPersonnel", "safetyComments",
]

REPORT_TABLES = {
    "drilling": {
        "field_sheet": "drilling_fields",
        "field_columns": DRILLING_FIELD_COLUMNS,
        "multi": {
            "survey_data": "drilling_survey",
            "bha_components": "drilling_bha",
            "operations": "drilling_operations",
            "fluid_losses": "drilling_fluid_losses",
            "bulks": "drilling_bulks",
        },
    },
    "completion": {
        "field_sheet": "completion_fields",
        "field_columns": COMPLETION_FIELD_COLUMNS,
        "multi": {
            "operations": "completion_operations",
            "bulks": "completion_bulks",
            "mud_products": "completion_mud_products",
            "perforation_intervals": "completion_intervals",
        },
    },
    "workover": {
        "field_sheet": "workover_fields",
        "field_columns": WORKOVER_FIELD_COLUMNS,
        "multi": {
            "operations": "workover_operations",
            "bulks": "workover_bulks",
            "mud_products": "workover_mud_products",
            "perforation_intervals": "workover_intervals",
        },
    },
}


ROW_COLUMNS = {
    "operations": ["from", "to", "hours", "op_code", "op_sub", "op_type", "operation_details", "system_op_type", "confirmed_op_type"],
    "bulks": ["bulk", "qty_start", "qty_used", "qty_end"],
    "fluid_losses": ["injected_volume_bbl", "returned_volume_bbl"],
    "survey_data": ["md", "incl", "azi", "tvd", "vse", "ns", "ew", "dls", "build"],
    "bha_components": ["component", "od", "id", "joints", "length"],
    "perforation_intervals": [
        "formation", "top_md", "base_md", "length", "density", "charges", "phase",
        "penetration", "diameter", "date", "status", "comments",
    ],
    "mud_products": ["product", "unit", "received", "used", "returned", "ending"],
}


# Complete UI labels for every persisted report field. These labels are
# presentation-only: field codes remain the stable API/database identifiers.
FIELD_LABELS_ZH = {
    "record_id": "记录标识",
    "event": "作业事件",
    "reportDate": "报告日期",
    "reportNo": "报告编号",
    "wellbore": "井筒",
    "rig": "井队/钻机",
    "primaryReason": "主要原因",
    "afeNumber": "AFE编号",
    "refDatum": "参考基准",
    "currentOps": "当前作业",
    "summary24h": "24小时作业总结",
    "forecast24h": "未来24小时计划",
    "otherRemarks": "其他备注",
    "wellboreNo": "井筒编号",
    "dfs": "开钻后天数",
    "todayMd": "今日测深",
    "prevMd": "上日测深",
    "progress": "日进尺",
    "rotHrsToday": "今日旋转钻进小时",
    "avgRopSlide": "平均滑动机械钻速",
    "avgRopRot": "平均旋转机械钻速",
    "dailyCost": "当日成本",
    "cumulativeCost": "累计成本",
    "afeCost": "AFE预算成本",
    "supervisor1": "主管1",
    "supervisor2": "主管2",
    "engineer": "工程师",
    "pamEngineer": "PAM工程师",
    "geologist": "地质师",
    "totalPersonnel": "现场总人数",
    "lastCasing": "上层套管",
    "lastCasingSize": "上层套管尺寸",
    "lastCasingDepth": "上层套管深度",
    "nextCasing": "下层套管",
    "nextCasingSize": "下层套管尺寸",
    "nextCasingDepth": "下层套管深度",
    "formTestType": "地层测试类型",
    "formTestEmw": "地层测试等效泥浆密度",
    "lastBopPressTest": "最近防喷器试压",
    "pumpRate": "泵排量",
    "pumpPress": "泵压",
    "stringWeightUp": "上提钻柱重量",
    "stringWeightDown": "下放钻柱重量",
    "stringWeightUpDown": "钻柱上下活动重量",
    "torqueOffBottom": "离底扭矩",
    "torqueOnBottom": "井底扭矩",
    "mudEngineer": "泥浆工程师",
    "sampleFrom": "泥浆取样位置",
    "mudType": "泥浆类型",
    "mudTime": "泥浆取样时间",
    "mudMd": "泥浆取样测深",
    "mudDensity": "泥浆密度",
    "mudTemperature": "泥浆温度",
    "rheologyTemp": "流变测试温度",
    "viscosity": "漏斗黏度",
    "pv": "塑性黏度",
    "yp": "动切力",
    "gel10s": "10秒静切力",
    "gel10m": "10分钟静切力",
    "gel30m": "30分钟静切力",
    "apiWl": "API滤失量",
    "oilPercent": "含油量",
    "waterPercent": "含水量",
    "sand": "含砂量",
    "ecd": "等效循环密度",
    "mudComments": "泥浆备注",
    "bitNo": "钻头序号",
    "bitSize": "钻头尺寸",
    "bitManufacturer": "钻头制造商",
    "bitSerial": "钻头序列号",
    "bitWearIodl": "钻头磨损内外径分级",
    "bitWearBgor": "钻头磨损特征分级",
    "bhaNo": "钻具组合编号",
    "bhaMdIn": "钻具组合入井测深",
    "bhaMdOut": "钻具组合出井测深",
    "bhaTotalLength": "钻具组合总长",
    "safetyIncident": "安全事故",
    "environmentIncident": "环境事故",
    "daysSinceRi": "距上次可记录事故天数",
    "daysSinceLta": "距上次损失工时事故天数",
    "incidentComments": "事故备注",
    "groundElev": "地面海拔",
    "afeMdDays": "AFE计划井深/天数",
    "completionNo": "完井编号",
    "dol": "现场作业天数",
    "rigContractName": "钻机合同名称",
    "description": "作业描述",
    "operationStartDate": "作业开始日期",
    "safetyComments": "安全备注",
    "workoverNo": "修井编号",
    "from": "开始时间",
    "to": "结束时间",
    "hours": "作业小时数",
    "op_code": "作业代码",
    "op_sub": "作业子类",
    "op_type": "作业类型",
    "operation_details": "作业明细",
    "system_op_type": "系统判定作业类型",
    "confirmed_op_type": "确认作业类型",
    "bulk": "物料名称",
    "qty_start": "期初数量",
    "qty_used": "使用数量",
    "qty_end": "期末数量",
    "injected_volume_bbl": "注入体积",
    "returned_volume_bbl": "返出体积",
    "md": "测量深度",
    "incl": "井斜角",
    "azi": "方位角",
    "tvd": "垂直深度",
    "vse": "垂直剖面位移",
    "ns": "南北位移",
    "ew": "东西位移",
    "dls": "狗腿度",
    "build": "造斜率",
    "component": "组件名称",
    "od": "外径",
    "id": "内径",
    "joints": "单根数量",
    "length": "长度",
    "formation": "地层",
    "top_md": "顶部测深",
    "base_md": "底部测深",
    "density": "射孔密度",
    "charges": "射孔弹",
    "phase": "相位角",
    "penetration": "穿透深度",
    "diameter": "孔径",
    "date": "日期",
    "status": "状态说明",
    "comments": "明细备注",
    "product": "产品名称",
    "unit": "单位",
    "received": "接收数量",
    "used": "使用数量",
    "returned": "退回数量",
    "ending": "期末数量",
}


# Only fields that carry natural-language content are exposed to translation tuning.
TRANSLATION_SCOPE_FIELDS = {
    "drilling": {
        "report_fields": [
            "event", "primaryReason", "currentOps", "summary24h", "forecast24h",
            "lastCasing", "nextCasing", "mudEngineer", "mudType", "mudComments",
            "bitManufacturer", "incidentComments", "otherRemarks",
        ],
        "operations": ["op_sub", "operation_details"],
        "bha_components": ["component"],
        "bulks": ["bulk"],
    },
    "completion": {
        "report_fields": [
            "event", "primaryReason", "currentOps", "summary24h", "forecast24h",
            "description", "supervisor1", "supervisor2", "engineer", "pamEngineer",
            "geologist", "safetyComments", "otherRemarks",
        ],
        "operations": ["op_sub", "operation_details"],
        "bulks": ["bulk"],
        "mud_products": ["product"],
        "perforation_intervals": ["formation", "charges", "status", "comments"],
    },
    "workover": {
        "report_fields": [
            "event", "primaryReason", "currentOps", "summary24h", "forecast24h",
            "description", "supervisor1", "supervisor2", "engineer", "pamEngineer",
            "geologist", "safetyComments", "otherRemarks",
        ],
        "operations": ["op_sub", "operation_details"],
        "bulks": ["bulk"],
        "mud_products": ["product"],
        "perforation_intervals": ["formation", "charges", "status", "comments"],
    },
}
